version: 2

sources:
  - name: raw
    schema: raw_data_circle
    description: data from Circle (French brand of eco-responsible and ethical sportswear)
    tables:
      - name: sales
        identifier: raw_cc_sales
        description: details about Circle stock
      - name: stock
        identifier: raw_cc_stock
        description: details about Circle sales
        tests:
          - unique:
              column_name: "(model || '_' || color || '_' || size)"